import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { listPRDs } from "@/lib/prd.functions";

export const Route = createFileRoute("/dashboard")({
  head: () => ({
    meta: [
      { title: "PRD History — Dashboard · Sachin Sharma" },
      {
        name: "description",
        content: "All PRDs generated by the AI Product Ops Stack.",
      },
    ],
  }),
  component: DashboardPage,
});

function DashboardPage() {
  const fetchPRDs = useServerFn(listPRDs);
  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ["prds"],
    queryFn: () => fetchPRDs(),
  });

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      <header className="border-b border-white/5">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-emerald-400 to-cyan-500 text-sm font-black text-black">
              S
            </div>
            <span className="text-sm font-semibold">AI Product Ops Stack</span>
          </Link>
          <div className="flex items-center gap-4 text-sm">
            <Link to="/demo" className="text-white/60 hover:text-white">
              + New PRD
            </Link>
            <Link to="/" className="text-white/60 hover:text-white">
              ← Back
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-6 py-12">
        <div className="flex items-end justify-between">
          <div>
            <h1 className="text-4xl font-black tracking-tight">PRD History</h1>
            <p className="mt-2 text-white/60">
              Every PRD generated by the system, newest first.
            </p>
          </div>
          <button
            onClick={() => refetch()}
            className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold transition hover:bg-white/10"
          >
            ↻ Refresh
          </button>
        </div>

        <div className="mt-8">
          {isLoading && <p className="text-white/50">Loading…</p>}
          {error && (
            <p className="text-red-300">
              {error instanceof Error ? error.message : "Failed to load."}
            </p>
          )}
          {data && data.length === 0 && (
            <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center">
              <p className="text-white/60">No PRDs yet.</p>
              <Link
                to="/demo"
                className="mt-4 inline-block rounded-full bg-emerald-400 px-5 py-2 text-sm font-bold text-black hover:bg-emerald-300"
              >
                Create your first PRD →
              </Link>
            </div>
          )}
          {data && data.length > 0 && (
            <ul className="space-y-3">
              {data.map((p) => (
                <li
                  key={p.id}
                  className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-5 transition hover:bg-white/[0.07]"
                >
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-base font-bold">{p.title}</div>
                    <div className="mt-1 text-xs text-white/40">
                      {new Date(p.created_at).toLocaleString()}
                    </div>
                  </div>
                  <div className="ml-4 flex shrink-0 items-center gap-2 text-xs">
                    {p.notion_url && (
                      <a
                        href={p.notion_url}
                        target="_blank"
                        rel="noreferrer"
                        className="rounded-full border border-white/10 bg-white/5 px-3 py-1 hover:bg-white/10"
                      >
                        📝 Notion
                      </a>
                    )}
                    {p.google_doc_url && (
                      <a
                        href={p.google_doc_url}
                        target="_blank"
                        rel="noreferrer"
                        className="rounded-full border border-white/10 bg-white/5 px-3 py-1 hover:bg-white/10"
                      >
                        📄 Doc
                      </a>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>
      </main>
    </div>
  );
}
