import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { getPRD } from "@/lib/prd.functions";

export const Route = createFileRoute("/p/$id")({
  head: ({ params }) => ({
    meta: [
      { title: "Shared PRD · AI Product Ops Stack" },
      {
        name: "description",
        content: "A PRD generated from a voice memo in seconds — by the AI Product Ops Stack.",
      },
      { property: "og:title", content: "AI-generated PRD" },
      {
        property: "og:description",
        content: `Generated by Sachin Kumar Sharma's AI Product Ops Stack · ID: ${params.id.slice(0, 8)}`,
      },
    ],
  }),
  component: SharePage,
});

function SharePage() {
  const { id } = Route.useParams();
  const fetchPRD = useServerFn(getPRD);
  const { data, isLoading, error } = useQuery({
    queryKey: ["prd", id],
    queryFn: () => fetchPRD({ data: { id } }),
  });

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      <header className="border-b border-white/5">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-emerald-400 to-cyan-500 text-sm font-black text-black">
              S
            </div>
            <span className="text-sm font-semibold">AI Product Ops Stack</span>
          </Link>
          <Link
            to="/demo"
            className="rounded-full bg-white px-4 py-1.5 text-xs font-bold text-black hover:bg-white/90"
          >
            Try it free →
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        {isLoading && <p className="text-white/50">Loading…</p>}
        {error && (
          <p className="text-red-300">
            {error instanceof Error ? error.message : "Not found"}
          </p>
        )}
        {data && (
          <>
            <div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-medium text-emerald-300">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
              Generated {new Date(data.created_at).toLocaleDateString()}
            </div>
            <h1 className="mt-5 text-4xl font-black tracking-tight md:text-5xl">
              {data.prd.title}
            </h1>

            <div className="mt-8 flex flex-wrap gap-2">
              {data.notion_url && (
                <a
                  href={data.notion_url}
                  target="_blank"
                  rel="noreferrer"
                  className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs hover:bg-white/10"
                >
                  📝 Open in Notion
                </a>
              )}
              {data.google_doc_url && (
                <a
                  href={data.google_doc_url}
                  target="_blank"
                  rel="noreferrer"
                  className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs hover:bg-white/10"
                >
                  📄 Open Google Doc
                </a>
              )}
            </div>

            <div className="mt-10 space-y-8">
              <Sec label="Problem">{data.prd.problem}</Sec>
              <Sec label="Target Users">{data.prd.targetUsers}</Sec>

              <ListBlock label="Goals" items={data.prd.goals} accent="text-emerald-400" />
              <ListBlock label="Non-Goals" items={data.prd.nonGoals} accent="text-rose-400" />

              <div>
                <div className="text-xs font-semibold uppercase tracking-wider text-cyan-400">
                  User Stories
                </div>
                <div className="mt-3 space-y-3">
                  {data.prd.userStories.map((us, i) => (
                    <div
                      key={i}
                      className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"
                    >
                      <div className="text-sm font-semibold">{us.story}</div>
                      <ul className="mt-3 space-y-1 text-sm text-white/70">
                        {us.acceptanceCriteria.map((ac, j) => (
                          <li key={j}>✓ {ac}</li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>

              <ListBlock
                label="Success Metrics"
                items={data.prd.successMetrics}
                accent="text-cyan-400"
              />
              <ListBlock label="Risks" items={data.prd.risks} accent="text-amber-400" />
              <ListBlock
                label="Open Questions"
                items={data.prd.openQuestions}
                accent="text-fuchsia-400"
              />
            </div>

            <div className="mt-16 rounded-3xl border border-white/10 bg-gradient-to-br from-emerald-500/10 to-cyan-500/10 p-8 text-center">
              <p className="text-sm text-white/60">Built by</p>
              <p className="mt-1 text-xl font-bold">Sachin Kumar Sharma</p>
              <p className="mt-1 text-xs text-white/50">
                Customer Success → Product Manager · AI-native PM
              </p>
              <Link
                to="/demo"
                className="mt-5 inline-block rounded-full bg-white px-6 py-2 text-sm font-bold text-black hover:bg-white/90"
              >
                Generate your own PRD →
              </Link>
            </div>
          </>
        )}
      </main>

      <footer className="border-t border-white/5 py-8 text-center text-xs text-white/40">
        Powered by Groq Whisper + Gemini 2.5 · © Sachin Kumar Sharma
      </footer>
    </div>
  );
}

function Sec({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="text-xs font-semibold uppercase tracking-wider text-white/50">{label}</div>
      <p className="mt-2 text-base text-white/85">{children}</p>
    </div>
  );
}

function ListBlock({
  label,
  items,
  accent,
}: {
  label: string;
  items: string[];
  accent: string;
}) {
  return (
    <div>
      <div className={`text-xs font-semibold uppercase tracking-wider ${accent}`}>{label}</div>
      <ul className="mt-2 space-y-1.5 text-sm text-white/80">
        {items.map((item, i) => (
          <li key={i} className="flex gap-2">
            <span className="text-white/30">·</span>
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
